hostname = '127.0.0.1'
port = 389
bind_dn = 'cn=readonly,dc=example,dc=org,dc=uk'
password = 'password'
search_base = 'ou=Users,dc=example,dc=org,dc=uk'
user_filter = '(&(objectClass=posixAccount)(uid=%s))'
lecturer_filter = '(&(objectClass=posixAccount)(uid=%s)(memberOf=cn=Lecturers,ou=Groups,dc=example,dc=org,dc=uk))'
admin_filter = '(&(objectClass=posixAccount)(uid=%s)(memberOf=cn=Admin,ou=Groups,dc=example,dc=org,dc=uk))'
